export enum SocialIconType {
  Facebook = "facebook",
  Instagram = "instagram",
  Linkedin = "linkedin",
  Twitter = "twitter",
  Youtube = "youtube",
  Pinterest = "pinterest",
  Telegram = "telegram",
  WhatsApp = "whatsapp",
  Twitch = "twitch",
  Tiktok = "tiktok",
  Snapchat = "snapchat",
  Behance = "behance",
  Dev = "dev",
  Discord = "discord",
  Figma = "figma",
  Github = "github",
  Gitlab = "gitlab",
}
